export type EventData = {
  id: number;
  name: string;
  slug: string;
  date?: string;
  venue?: string;
  category?: string;
  access?: "RBU only" | "Open to all";
  prize?: string;
};

export const eventsData: EventData[] = [
  {
    id: 1,
    name: "Naaqaab",
    slug: "naaqaab",
    date: "21st Feb 2026",
    venue: "MBA Auditorium",
    category: "Dramatics",
    access: "Open to all",
    prize: "₹10,000",
  },
  {
    id: 2,
    name: "Footsteps",
    slug: "footsteps",
    date: "21st Feb 2026",
    venue: "OAT",
    category: "Dance",
    access: "Open to all",
    prize: "₹10,000",
  },
  {
    id: 7,
    name: "Vibrato",
    slug: "vibrato",
    date: "22nd Feb 2026",
    venue: "MBA Auditorium",
    category: "Music",
    access: "Open to all",
    prize: "₹10,000",
  },
  {
    id: 3,
    name: "Art Affairs",
    slug: "art-affairs",
    date: "23rd Feb 2026",
    venue: "OAT Venue",
    category: "Fine Arts",
    access: "Open to all",
    prize: "₹6,000",
  },
  {
    id: 4,
    name: "Picasso",
    slug: "picasso",
    date: "22nd Feb 2026",
    venue: "Basketball Court",
    category: "Media",
    access: "RBU only",
    prize: "₹6,000",
  },
  {
    id: 5,
    name: "Quizzeus",
    slug: "quizzeus",
    date: "23rd Feb 2026",
    venue: "G-Block Classroom",
    category: "Quiz",
    access: "Open to all",
    prize: "₹4,000",
  },
  {
    id: 6,
    name: "Minute To Win It",
    slug: "minute-to-win-it",
    date: "21st Feb 2026",
    venue: "Basketball Court",
    category: "Fun Event",
    access: "RBU only",
    prize: "₹4,000",
  },
  {
    id: 8,
    name: "RBU Got Latent",
    slug: "rbu-got-latent",
    date: "23rd Feb 2026",
    venue: "EN Auditorium",
    category: "Talent",
    access: "RBU only",
    prize: "₹10,000",
  },
  {
    id: 9,
    name: "Ingenium",
    slug: "ingenium",
    date: "22nd Feb 2026",
    venue: "DT-702",
    category: "Showcase",
    access: "Open to all",
  },
  {
    id: 10,
    name: "Persona",
    slug: "persona",
    date: "21st Feb 2026",
    venue: "DT-906",
    category: "Talent",
    access: "Open to all",
  },
  {
    id: 11,
    name: "Virtual Gaming",
    slug: "virtual-gaming",
    date: "22nd Feb 2026",
    venue: "DT-303, DT-306",
    category: "Gaming",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 12,
    name: "Dalal Street",
    slug: "dalal-street",
    date: "23rd Feb 2026",
    venue: "G-Block Classroom",
    category: "Finance",
    access: "RBU only",
    prize: "₹7,000",
  },
  {
    id: 13,
    name: "Cinecrypt",
    slug: "cinecrypt",
    date: "21st Feb 2026",
    venue: "DT-109, DT-209",
    category: "Entertainment",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 14,
    name: "Hyroxx",
    slug: "hyroxx",
    date: "21st Feb 2026",
    venue: "Football Ground",
    category: "Sports",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 15,
    name: "Escape Room",
    slug: "escape-room",
    date: "22nd Feb 2026",
    venue: "DT-701",
    category: "Adventure",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 16,
    name: "Auto Expo",
    slug: "auto-expo",
    date: "24th Feb 2026",
    venue: "EN Parking",
    category: "Showcase",
    access: "Open to all",
  },
  {
    id: 17,
    name: "Movie Eve",
    slug: "movie-eve",
    date: "24th Feb 2026",
    venue: "MBA Auditorium",
    category: "Entertainment",
    access: "Open to all",
  },
  {
    id: 18,
    name: "Traitors",
    slug: "traitors",
    date: "22nd Feb 2026",
    venue: "DT-301",
    category: "Strategy",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 19,
    name: "Aarambh",
    slug: "aarambh",
    date: "22nd Feb 2026",
    venue: "Venue DR-301",
    category: "Opening",
    access: "Open to all",
  },
  {
    id: 20,
    name: "Central Cartel",
    slug: "central-cartel",
    date: "21st Feb 2026",
    venue: "Basketball Court",
    category: "Management",
    access: "Open to all",
  },
  {
    id: 21,
    name: "Cultural Night",
    slug: "cultural-night",
    date: "26th Feb 2026",
    venue: "P26 Dome",
    category: "Cultural",
    access: "Open to all",
  },
  {
    id: 22,
    name: "Detox Room",
    slug: "detox-room",
    date: "22nd Feb 2026",
    venue: "EN Auditorium",
    category: "Wellness",
    access: "RBU only",
  },
  {
    id: 23,
    name: "DJ Garv",
    slug: "dj-garv",
    date: "26th Feb 2026",
    venue: "Basketball Court",
    category: "Music",
    access: "Open to all",
  },
  {
    id: 24,
    name: "Festive Freeway",
    slug: "festive-freeway",
    date: "21st Feb 2026",
    venue: "Basketball Court",
    category: "Informals",
    access: "RBU only",
  },
  {
    id: 25,
    name: "Food Stalls",
    slug: "food-stalls",
    date: "21st-24th Feb 2026",
    venue: "Campus Food Court",
    category: "Lifestyle",
    access: "Open to all",
  },
];
