export type EventData = {
  id: number;
  name: string;
  slug: string;
  date?: string;
  venue?: string;
  category?: string;
  access?: "RBU only" | "Open to all";
  prize?: string;
};

export const eventsData: EventData[] = [
  {
    id: 1,
    name: "Naaqaab",
    slug: "naaqaab",
    date: "21st Feb 2026",
    venue: "MBA Auditorium",
    category: "Dramatics",
    access: "Open to all",
    prize: "₹10,000",
  },
  {
    id: 2,
    name: "Footsteps",
    slug: "footsteps",
    date: "21st Feb 2026",
    venue: "OAT",
    category: "Dance",
    access: "Open to all",
    prize: "₹10,000",
  },
  {
    id: 7,
    name: "Vibrato",
    slug: "vibrato",
    date: "22nd Feb 2026",
    venue: "MBA Auditorium",
    category: "Music",
    access: "Open to all",
    prize: "₹10,000",
  },
  {
    id: 3,
    name: "Art Affairs",
    slug: "art-affairs",
    date: "23rd Feb 2026",
    venue: "OAT Venue",
    category: "Fine Arts",
    access: "Open to all",
    prize: "₹6,000",
  },
  {
    id: 4,
    name: "Picasso",
    slug: "picasso",
    date: "22nd Feb 2026",
    venue: "Basketball Court",
    category: "Media",
    access: "Open to all",
    prize: "₹6,000",
  },
  {
    id: 5,
    name: "Quizzeus",
    slug: "quizzeus",
    date: "23rd Feb 2026",
    venue: "G-Block Classroom",
    category: "Quiz",
    access: "Open to all",
    prize: "₹4,000",
  },
  {
    id: 6,
    name: "Minute To Win It",
    slug: "minute-to-win-it",
    date: "21st Feb 2026",
    venue: "Basketball Court",
    category: "Fun Event",
    access: "RBU only",
    prize: "₹4,000",
  },
  {
    id: 8,
    name: "RBU's Got Talent",
    slug: "rbu-got-talent",
    date: "23rd Feb 2026",
    venue: "EN Auditorium",
    category: "Talent",
    access: "RBU only",
    prize: "₹10,000",
  },
  {
    id: 9,
    name: "Ingenium",
    slug: "ingenium",
    date: "22nd Feb 2026",
    venue: "EN Parking",
    category: "Technical",
    access: "RBU only",
    prize: "₹10,000",
  },
  {
    id: 10,
    name: "Persona",
    slug: "persona",
    date: "22nd Feb 2026",
    venue: "DT-906",
    category: "Personality",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 11,
    name: "Virtual Gaming",
    slug: "virtual-gaming",
    date: "22nd Feb 2026",
    venue: "DT-109, DT-209",
    category: "Gaming",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 12,
    name: "Dalal Street",
    slug: "dalal-street",
    date: "23rd Feb 2026",
    venue: "G-Block Classroom",
    category: "Finance",
    access: "RBU only",
    prize: "₹7,000",
  },
  {
    id: 13,
    name: "Cinecrypt",
    slug: "cinecrypt",
    date: "21st Feb 2026",
    venue: "DT-109, DT-209",
    category: "Entertainment",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 14,
    name: "Hyroxx",
    slug: "hyroxx",
    date: "21st Feb 2026",
    venue: "Football Ground",
    category: "Sports",
    access: "RBU only",
    prize: "₹5,000",
  },
  {
    id: 15,
    name: "Escape Room",
    slug: "escape-room",
    date: "22nd Feb 2026",
    venue: "DT-701",
    category: "Adventure",
    access: "RBU only",
    prize: "₹5,000",
  },

  {
    id: 17,
    name: "Movie Eve",
    slug: "movie-eve",
    date: "24th Feb 2026",
    venue: "MBA Auditorium",
    category: "Entertainment",
    access: "Open to all",
  },
  {
    id: 18,
    name: "Traitors",
    slug: "traitors",
    date: "22nd Feb 2026",
    venue: "DT-301",
    category: "Strategy",
    access: "RBU only",
    prize: "₹5,000",
  },
];